version: '3.1'

services:

  app:
    build: netmag
    command: bash -c "sleep 30 && python3 manage.py makemigrations && python3 manage.py makemigrations polls && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - dtbs
    networks:
      - backend
 
  dtbs:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - backend

networks:
    backend: 
